#define DEVICES_CONSOLE_CLINIT_ 0 /* <clinit> [devices.Console] */
#define DEVICES_CONSOLE_GETBYTES 1 /* getBytes [devices.Console] */
#define DEVICES_CONSOLE_PRINTLN 2 /* println [devices.Console] */
#define DEVICES_CONSOLE_PRINTLN_ 3 /* println [devices.Console] */
#define DEVICES_X86WRITER_INIT_ 4 /* <init> [devices.X86Writer] */
#define DEVICES_X86WRITER_NWRITE 5 /* nwrite [devices.X86Writer] */
#define DEVICES_X86WRITER_WRITE 6 /* write [devices.X86Writer] */
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_INIT_ 7 /* <init> [java.lang.AbstractStringBuilder] */
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_APPEND 8 /* append [java.lang.AbstractStringBuilder] */
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_APPEND_ 9 /* append [java.lang.AbstractStringBuilder] */
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_APPENDNULL 10 /* appendNull [java.lang.AbstractStringBuilder] */
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_ENSURECAPACITYINTERNAL 11 /* ensureCapacityInternal [java.lang.AbstractStringBuilder] */
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_EXPANDCAPACITY 12 /* expandCapacity [java.lang.AbstractStringBuilder] */
#define JAVA_LANG_ARITHMETICEXCEPTION_INIT_ 13 /* <init> [java.lang.ArithmeticException] */
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION_INIT_ 14 /* <init> [java.lang.ArrayIndexOutOfBoundsException] */
#define JAVA_LANG_ASSERTIONERROR_INIT_ 15 /* <init> [java.lang.AssertionError] */
#define JAVA_LANG_CLASS_CLINIT_ 16 /* <clinit> [java.lang.Class] */
#define JAVA_LANG_CLASS_DESIREDASSERTIONSTATUS 17 /* desiredAssertionStatus [java.lang.Class] */
#define JAVA_LANG_CLASS_GETPRIMITIVECLASS 18 /* getPrimitiveClass [java.lang.Class] */
#define JAVA_LANG_DOUBLE_CLINIT_ 19 /* <clinit> [java.lang.Double] */
#define JAVA_LANG_DOUBLE_DOUBLETORAWLONGBITS 20 /* doubleToRawLongBits [java.lang.Double] */
#define JAVA_LANG_DOUBLE_LONGBITSTODOUBLE 21 /* longBitsToDouble [java.lang.Double] */
#define JAVA_LANG_ERROR_INIT_ 22 /* <init> [java.lang.Error] */
#define JAVA_LANG_EXCEPTION_INIT_ 23 /* <init> [java.lang.Exception] */
#define JAVA_LANG_EXCEPTION_INIT__ 24 /* <init> [java.lang.Exception] */
#define JAVA_LANG_FLOAT_CLINIT_ 25 /* <clinit> [java.lang.Float] */
#define JAVA_LANG_FLOAT_FLOATTORAWINTBITS 26 /* floatToRawIntBits [java.lang.Float] */
#define JAVA_LANG_ILLEGALARGUMENTEXCEPTION_INIT_ 27 /* <init> [java.lang.IllegalArgumentException] */
#define JAVA_LANG_ILLEGALMONITORSTATEEXCEPTION_INIT_ 28 /* <init> [java.lang.IllegalMonitorStateException] */
#define JAVA_LANG_INDEXOUTOFBOUNDSEXCEPTION_INIT_ 29 /* <init> [java.lang.IndexOutOfBoundsException] */
#define JAVA_LANG_INDEXOUTOFBOUNDSEXCEPTION_INIT__ 30 /* <init> [java.lang.IndexOutOfBoundsException] */
#define JAVA_LANG_INTEGER_CLINIT_ 31 /* <clinit> [java.lang.Integer] */
#define JAVA_LANG_INTEGER_GETCHARS 32 /* getChars [java.lang.Integer] */
#define JAVA_LANG_INTEGER_STRINGSIZE 33 /* stringSize [java.lang.Integer] */
#define JAVA_LANG_MATH_CLINIT_ 34 /* <clinit> [java.lang.Math] */
#define JAVA_LANG_MATH_INIT_ 35 /* <init> [java.lang.Math] */
#define JAVA_LANG_MATH_MIN 36 /* min [java.lang.Math] */
#define JAVA_LANG_MATH_POWEROFTWOD 37 /* powerOfTwoD [java.lang.Math] */
#define JAVA_LANG_NEGATIVEARRAYSIZEEXCEPTION_INIT_ 38 /* <init> [java.lang.NegativeArraySizeException] */
#define JAVA_LANG_NULLPOINTEREXCEPTION_INIT_ 39 /* <init> [java.lang.NullPointerException] */
#define JAVA_LANG_OBJECT_INIT_ 40 /* <init> [java.lang.Object] */
#define JAVA_LANG_OUTOFMEMORYERROR_INIT_ 41 /* <init> [java.lang.OutOfMemoryError] */
#define JAVA_LANG_RUNTIMEEXCEPTION_INIT_ 42 /* <init> [java.lang.RuntimeException] */
#define JAVA_LANG_RUNTIMEEXCEPTION_INIT__ 43 /* <init> [java.lang.RuntimeException] */
#define JAVA_LANG_STRING_INITFROMCHARARRAY 44 /* <init> [java.lang.String] */
#define JAVA_LANG_STRING_INIT__ 45 /* <init> [java.lang.String] */
#define JAVA_LANG_STRING_CHARAT 46 /* charAt [java.lang.String] */
#define JAVA_LANG_STRING_GETCHARS 47 /* getChars [java.lang.String] */
#define JAVA_LANG_STRING_LENGTH 48 /* length [java.lang.String] */
#define JAVA_LANG_STRINGBUILDER_INIT_ 49 /* <init> [java.lang.StringBuilder] */
#define JAVA_LANG_STRINGBUILDER_APPEND_ 50 /* append [java.lang.StringBuilder] */
#define JAVA_LANG_STRINGBUILDER_APPEND__ 51 /* append [java.lang.StringBuilder] */
#define JAVA_LANG_STRINGBUILDER_APPEND___ 52 /* append [java.lang.StringBuilder] */
#define JAVA_LANG_STRINGBUILDER_TOSTRING 53 /* toString [java.lang.StringBuilder] */
#define JAVA_LANG_STRINGINDEXOUTOFBOUNDSEXCEPTION_INIT_ 54 /* <init> [java.lang.StringIndexOutOfBoundsException] */
#define JAVA_LANG_SYSTEM_CLINIT_ 55 /* <clinit> [java.lang.System] */
#define JAVA_LANG_SYSTEM_ARRAYCOPY 56 /* arraycopy [java.lang.System] */
#define JAVA_LANG_SYSTEM_REGISTERNATIVES 57 /* registerNatives [java.lang.System] */
#define JAVA_LANG_THROWABLE_CLINIT_ 58 /* <clinit> [java.lang.Throwable] */
#define JAVA_LANG_THROWABLE_INIT_ 59 /* <init> [java.lang.Throwable] */
#define JAVA_LANG_THROWABLE_INIT__ 60 /* <init> [java.lang.Throwable] */
#define JAVA_LANG_THROWABLE_FILLINSTACKTRACE 61 /* fillInStackTrace [java.lang.Throwable] */
#define JAVA_LANG_THROWABLE_FILLINSTACKTRACE_ 62 /* fillInStackTrace [java.lang.Throwable] */
#define JAVA_LANG_VIRTUALMACHINEERROR_INIT_ 63 /* <init> [java.lang.VirtualMachineError] */
#define JAVA_UTIL_ARRAYS_CLINIT_ 64 /* <clinit> [java.util.Arrays] */
#define JAVA_UTIL_ARRAYS_INIT_ 65 /* <init> [java.util.Arrays] */
#define JAVA_UTIL_ARRAYS_COPYOF 66 /* copyOf [java.util.Arrays] */
#define JAVA_UTIL_ARRAYS_COPYOFRANGE 67 /* copyOfRange [java.util.Arrays] */
#define SCJHELLOWORLD_DELAY_INIT_ 68 /* <init> [scjhelloworld.Delay] */
#define SCJHELLOWORLD_DELAY_DELAY 69 /* delay [scjhelloworld.Delay] */
#define SCJHELLOWORLD_DELAY_DELAYTICKS 70 /* delayTicks [scjhelloworld.Delay] */
#define SCJHELLOWORLD_LED_INIT_ 71 /* <init> [scjhelloworld.Led] */
#define SCJHELLOWORLD_LED_LEDSTATUS 72 /* ledStatus [scjhelloworld.Led] */
#define SCJHELLOWORLD_LED_OFF 73 /* off [scjhelloworld.Led] */
#define SCJHELLOWORLD_LED_ON 74 /* on [scjhelloworld.Led] */
#define SCJHELLOWORLD_TESTPROCESS_P1_INIT_ 75 /* <init> [scjhelloworld.TestProcess$P1] */
#define SCJHELLOWORLD_TESTPROCESS_P1_INIT__ 76 /* <init> [scjhelloworld.TestProcess$P1] */
#define SCJHELLOWORLD_TESTPROCESS_P1_CATCHERROR 77 /* catchError [scjhelloworld.TestProcess$P1] */
#define SCJHELLOWORLD_TESTPROCESS_P1_RUN 78 /* run [scjhelloworld.TestProcess$P1] */
#define SCJHELLOWORLD_TESTPROCESS_P2_INIT_ 79 /* <init> [scjhelloworld.TestProcess$P2] */
#define SCJHELLOWORLD_TESTPROCESS_P2_INIT__ 80 /* <init> [scjhelloworld.TestProcess$P2] */
#define SCJHELLOWORLD_TESTPROCESS_P2_CATCHERROR 81 /* catchError [scjhelloworld.TestProcess$P2] */
#define SCJHELLOWORLD_TESTPROCESS_P2_RUN 82 /* run [scjhelloworld.TestProcess$P2] */
#define SCJHELLOWORLD_TESTPROCESS_ACCESS_0 83 /* access$0 [scjhelloworld.TestProcess] */
#define SCJHELLOWORLD_TESTPROCESS_ACCESS_1 84 /* access$1 [scjhelloworld.TestProcess] */
#define SCJHELLOWORLD_TESTPROCESS_ACCESS_2 85 /* access$2 [scjhelloworld.TestProcess] */
#define SCJHELLOWORLD_TESTPROCESS_MAIN 86 /* main [scjhelloworld.TestProcess] */
#define VM_CLOCKINTERRUPTHANDLER_YIELD 87 /* yield [vm.ClockInterruptHandler] */
#define VM_PROCESS_PROCESSEXECUTOR_INIT_ 88 /* <init> [vm.Process$ProcessExecutor] */
#define VM_PROCESS_PROCESSEXECUTOR_RUN 89 /* run [vm.Process$ProcessExecutor] */
#define VM_PROCESS_SP_INIT_ 90 /* <init> [vm.Process$SP] */
#define VM_PROCESS_SP_INIT__ 91 /* <init> [vm.Process$SP] */
#define VM_PROCESS_X86_32SP_INIT_ 92 /* <init> [vm.Process$X86_32SP] */
#define VM_PROCESS_X86_32SP_INIT__ 93 /* <init> [vm.Process$X86_32SP] */
#define VM_PROCESS_X86_64SP_INIT_ 94 /* <init> [vm.Process$X86_64SP] */
#define VM_PROCESS_X86_64SP_INIT__ 95 /* <init> [vm.Process$X86_64SP] */
#define VM_PROCESS_INIT_ 96 /* <init> [vm.Process] */
#define VM_PROCESS_ACCESS_0 97 /* access$0 [vm.Process] */
#define VM_PROCESS_ACCESS_1 98 /* access$1 [vm.Process] */
#define VM_PROCESS_EXECUTEWITHSTACK 99 /* executeWithStack [vm.Process] */
#define VM_PROCESS_INITIALIZE 100 /* initialize [vm.Process] */
#define VM_PROCESS_TRANSFER 101 /* transfer [vm.Process] */
#define VM_PROCESS_TRANSFERTO 102 /* transferTo [vm.Process] */
#define NUMRUNTIMEEXCEPTIONS 11
#define NUMBEROFCLASSINITIALIZERS 4
#define INVOKECLASSINITIALIZERS
#define NUMBEROFCONSTANTS 28
#define NUMBEROFCLASSINITIALIZERS_var NUMBEROFCLASSINITIALIZERS
#define NUMBEROFCONSTANTS_var NUMBEROFCONSTANTS
#define NUMBEROFMETHODS 103
#define JAVA_LANG_STRING_INITFROMCHARARRAY_var JAVA_LANG_STRING_INITFROMCHARARRAY
#define JAVA_LANG_CLASSCASTEXCEPTION_INIT__var JAVA_LANG_CLASSCASTEXCEPTION_INIT_
#define JAVA_LANG_ARITHMETICEXCEPTION_INIT__var JAVA_LANG_ARITHMETICEXCEPTION_INIT_
#define JAVA_LANG_OUTOFMEMORYERROR_INIT__var JAVA_LANG_OUTOFMEMORYERROR_INIT_
#define JAVA_LANG_NULLPOINTEREXCEPTION_INIT__var JAVA_LANG_NULLPOINTEREXCEPTION_INIT_
#define JAVA_LANG_OBJECT_CLONE_var JAVA_LANG_OBJECT_CLONE
#define VM_INTERRUPTDISPATCHER_INTERRUPT_var VM_INTERRUPTDISPATCHER_INTERRUPT
#define TASKS_MODBUSDISPATCHER_DISPATCH_var TASKS_MODBUSDISPATCHER_DISPATCH
#define JAVA_LANG_STRINGBUFFER_APPEND_var JAVA_LANG_STRINGBUFFER_APPEND
#define JAVA_LANG_STRINGBUILDER_APPEND_var JAVA_LANG_STRINGBUILDER_APPEND
#define JAVA_LANG_STRING_INIT__var JAVA_LANG_STRING_INIT_
#define JAVA_LANG_FLOAT_TOSTRING_var JAVA_LANG_FLOAT_TOSTRING
#define JAVA_LANG_THREAD_INIT_DEFAULT_var JAVA_LANG_THREAD_INIT_DEFAULT
#define JAVA_LANG_CLASSCASTEXCEPTION_INIT_ -1
#define JAVA_LANG_OBJECT_CLONE -1
#define VM_INTERRUPTDISPATCHER_INTERRUPT -1
#define TASKS_MODBUSDISPATCHER_DISPATCH -1
#define JAVA_LANG_STRINGBUFFER_APPEND -1
#define JAVA_LANG_STRINGBUILDER_APPEND -1
#define JAVA_LANG_STRING_INIT_ -1
#define JAVA_LANG_FLOAT_TOSTRING -1
#define JAVA_LANG_THREAD_INIT_DEFAULT -1

#define ALOAD_0_OPCODE_USED 
#define ALOAD_1_OPCODE_USED 
#define RETURN_OPCODE_USED 
#define PUTFIELD_OPCODE_USED 
#define INVOKESPECIAL_OPCODE_USED 
#define INVOKESTATIC_OPCODE_USED 
#define ARRAYLENGTH_OPCODE_USED 
#define DEVICES_CONSOLE_CLINIT__USED
#define INITIALIZEEXCEPTION_USED
#define HANDLEATHROW_USED
#define CREATEARRAY_USED
#define GETCLASSINDEX_USED
#define HANDLENEWCLASSINDEX_USED
#define ENTERMETHODINTERPRETER_USED
#define DEVICES_CONSOLE_GETBYTES_USED
#define DEVICES_CONSOLE_PRINTLN_USED
#define DEVICES_CONSOLE_PRINTLN__USED
#define DEVICES_X86WRITER_INIT__USED
#define JAVA_LANG_OBJECT_INIT__USED
#define DEVICES_X86WRITER_WRITE_USED
#define N_DEVICES_X86WRITER_NWRITE_USED
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_INIT__USED
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_APPEND_USED
#define INITIALIZESTRINGCONSTANT_USED
#define JAVA_LANG_STRINGBUILDER_APPEND___USED
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_APPEND__USED
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_APPENDNULL_USED
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_ENSURECAPACITYINTERNAL_USED
#define JAVA_LANG_ABSTRACTSTRINGBUILDER_EXPANDCAPACITY_USED
#define IMUL_USED
#define JAVA_UTIL_ARRAYS_COPYOF_USED
#define JAVA_LANG_ARRAYINDEXOUTOFBOUNDSEXCEPTION_INIT__USED
#define JAVA_LANG_INDEXOUTOFBOUNDSEXCEPTION_INIT__USED
#define JAVA_LANG_ASSERTIONERROR_INIT__USED
#define JAVA_LANG_ERROR_INIT__USED
#define JAVA_LANG_DOUBLE_CLINIT__USED
#define N_JAVA_LANG_CLASS_GETPRIMITIVECLASS_USED
#define JAVA_LANG_EXCEPTION_INIT__USED
#define JAVA_LANG_EXCEPTION_INIT___USED
#define JAVA_LANG_FLOAT_CLINIT__USED
#define JAVA_LANG_ILLEGALARGUMENTEXCEPTION_INIT__USED
#define JAVA_LANG_ILLEGALMONITORSTATEEXCEPTION_INIT__USED
#define JAVA_LANG_RUNTIMEEXCEPTION_INIT__USED
#define JAVA_LANG_INDEXOUTOFBOUNDSEXCEPTION_INIT___USED
#define JAVA_LANG_INTEGER_CLINIT__USED
#define JAVA_LANG_INTEGER_GETCHARS_USED
#define IDIV_USED
#define JAVA_LANG_INTEGER_STRINGSIZE_USED
#define JAVA_LANG_MATH_CLINIT__USED
#define GETCLASS_USED
#define N_JAVA_LANG_CLASS_DESIREDASSERTIONSTATUS_USED
#define HANDLELDCWITHINDEX_USED
#define N_JAVA_LANG_FLOAT_FLOATTORAWINTBITS_USED
#define N_JAVA_LANG_DOUBLE_DOUBLETORAWLONGBITS_USED
#define JAVA_LANG_MATH_INIT__USED
#define JAVA_LANG_MATH_MIN_USED
#define JAVA_LANG_MATH_POWEROFTWOD_USED
#define HANDLELONGOPERATOR_USED
#define HANDLELSHL_USED
#define N_JAVA_LANG_DOUBLE_LONGBITSTODOUBLE_USED
#define JAVA_LANG_NEGATIVEARRAYSIZEEXCEPTION_INIT__USED
#define JAVA_LANG_RUNTIMEEXCEPTION_INIT___USED
#define JAVA_LANG_STRING_INIT___USED
#define JAVA_LANG_STRING_CHARAT_USED
#define JAVA_LANG_STRING_GETCHARS_USED
#define N_JAVA_LANG_SYSTEM_ARRAYCOPY_USED
#define JAVA_LANG_STRING_LENGTH_USED
#define JAVA_LANG_STRINGBUILDER_INIT__USED
#define JAVA_LANG_STRINGBUILDER_APPEND__USED
#define JAVA_LANG_STRINGBUILDER_APPEND____USED
#define JAVA_LANG_STRINGBUILDER_TOSTRING_USED
#define JAVA_LANG_STRINGINDEXOUTOFBOUNDSEXCEPTION_INIT__USED
#define JAVA_LANG_SYSTEM_CLINIT__USED
#define N_JAVA_LANG_SYSTEM_REGISTERNATIVES_USED
#define JAVA_LANG_THROWABLE_INIT__USED
#define HANDLEMONITORENTEREXIT_USED
#define JAVA_LANG_THROWABLE_INIT___USED
#define JAVA_LANG_THROWABLE_FILLINSTACKTRACE_USED
#define N_JAVA_LANG_THROWABLE_FILLINSTACKTRACE__USED
#define JAVA_LANG_VIRTUALMACHINEERROR_INIT__USED
#define JAVA_UTIL_ARRAYS_CLINIT__USED
#define JAVA_UTIL_ARRAYS_INIT__USED
#define JAVA_UTIL_ARRAYS_COPYOFRANGE_USED
#define SCJHELLOWORLD_DELAY_INIT__USED
#define SCJHELLOWORLD_DELAY_DELAY_USED
#define N_SCJHELLOWORLD_DELAY_DELAYTICKS_USED
#define SCJHELLOWORLD_LED_INIT__USED
#define SCJHELLOWORLD_LED_OFF_USED
#define N_SCJHELLOWORLD_LED_LEDSTATUS_USED
#define SCJHELLOWORLD_LED_ON_USED
#define SCJHELLOWORLD_TESTPROCESS_P1_INIT__USED
#define SCJHELLOWORLD_TESTPROCESS_P1_INIT___USED
#define SCJHELLOWORLD_TESTPROCESS_P1_CATCHERROR_USED
#define SCJHELLOWORLD_TESTPROCESS_P1_RUN_USED
#define SCJHELLOWORLD_TESTPROCESS_ACCESS_0_USED
#define SCJHELLOWORLD_TESTPROCESS_ACCESS_1_USED
#define SCJHELLOWORLD_TESTPROCESS_P2_INIT__USED
#define SCJHELLOWORLD_TESTPROCESS_P2_INIT___USED
#define SCJHELLOWORLD_TESTPROCESS_P2_CATCHERROR_USED
#define SCJHELLOWORLD_TESTPROCESS_P2_RUN_USED
#define SCJHELLOWORLD_TESTPROCESS_ACCESS_2_USED
#define SCJHELLOWORLD_TESTPROCESS_MAIN_USED
#define VM_CLOCKINTERRUPTHANDLER_YIELD_USED
#define VM_PROCESS_PROCESSEXECUTOR_INIT__USED
#define VM_PROCESS_PROCESSEXECUTOR_RUN_USED
#define VM_PROCESS_ACCESS_0_USED
#define DISPATCHINTERFACE_USED
#define VM_PROCESS_ACCESS_1_USED
#define VM_PROCESS_SP_INIT__USED
#define VM_PROCESS_SP_INIT___USED
#define VM_PROCESS_X86_32SP_INIT__USED
#define VM_PROCESS_X86_32SP_INIT___USED
#define VM_PROCESS_X86_64SP_INIT__USED
#define VM_PROCESS_X86_64SP_INIT___USED
#define VM_PROCESS_INIT__USED
#define VM_PROCESS_INITIALIZE_USED
#define N_VM_PROCESS_EXECUTEWITHSTACK_USED
#define VM_PROCESS_TRANSFERTO_USED
#define N_VM_PROCESS_TRANSFER_USED
#define UNIMPLEMENTED_NATIVE_FUNCTION_USED
#define LDC_STRING
#define LDC_FLOAT
#define LDC_DOUBLE
#define LDC_LONG
#define N_DEVICES_X86WRITER_NWRITE 5
#define N_JAVA_LANG_CLASS_CLINIT_ 16
#define N_JAVA_LANG_CLASS_DESIREDASSERTIONSTATUS 17
#define N_JAVA_LANG_CLASS_GETPRIMITIVECLASS 18
#define N_JAVA_LANG_DOUBLE_DOUBLETORAWLONGBITS 20
#define N_JAVA_LANG_DOUBLE_LONGBITSTODOUBLE 21
#define N_JAVA_LANG_FLOAT_FLOATTORAWINTBITS 26
#define N_JAVA_LANG_SYSTEM_ARRAYCOPY 56
#define N_JAVA_LANG_SYSTEM_REGISTERNATIVES 57
#define N_JAVA_LANG_THROWABLE_CLINIT_ 58
#define N_JAVA_LANG_THROWABLE_FILLINSTACKTRACE_ 62
#define N_SCJHELLOWORLD_DELAY_DELAYTICKS 70
#define N_SCJHELLOWORLD_LED_LEDSTATUS 72
#define N_VM_PROCESS_EXECUTEWITHSTACK 99
#define N_VM_PROCESS_TRANSFER 101
#define TASKS_PROCESSCHEDULER_GETNEXTPROCESS_VTABLEINDEX -1
